# Generated by Django 5.0.1 on 2024-03-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_price',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
