# Generated by Django 5.0.1 on 2024-02-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=True, upload_to=''),
        ),
    ]
