# Generated by Django 5.0.1 on 2024-03-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_related_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='related_posts',
            field=models.ManyToManyField(blank=True, to='post.post', verbose_name='پست های مشابه'),
        ),
    ]
