# Generated by Django 5.0.1 on 2024-02-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='img',
        ),
    ]
