# Generated by Django 5.0.1 on 2024-03-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_reply_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='reply',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='نام و نام خانوادگی'),
        ),
    ]
