# Generated by Django 5.0.1 on 2024-02-11 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='write',
            new_name='writer',
        ),
    ]
