# Generated by Django 5.0.1 on 2024-03-19 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_rename_comment_reply_post_alter_reply_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='post',
            new_name='comment',
        ),
    ]
