# Generated by Django 5.0.1 on 2024-02-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='crated_time',
            field=models.DateTimeField(null=True),
        ),
    ]
