# Generated by Django 5.0.1 on 2024-02-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='crated_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer',
            field=models.CharField(max_length=30),
        ),
    ]
