# Generated by Django 5.0.1 on 2024-03-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='x',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
