# Generated by Django 5.0.1 on 2024-03-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_post_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='x',
        ),
    ]
